[2024-05-29T17:02:59.951+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T17:03:00.184+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-05-29T17:03:00.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_1.task_4 scheduled__2024-03-10T00:00:00+00:00 [queued]>
[2024-05-29T17:03:00.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T17:03:00.497+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task_4> on 2024-03-10 00:00:00+00:00
[2024-05-29T17:03:00.577+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T17:03:00.594+0000] {standard_task_runner.py:63} INFO - Started process 352 to run task
[2024-05-29T17:03:00.589+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'test_1', 'task_4', 'scheduled__2024-03-10T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpds7w0dct']
[2024-05-29T17:03:00.663+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask task_4
[2024-05-29T17:03:01.292+0000] {task_command.py:426} INFO - Running <TaskInstance: test_1.task_4 scheduled__2024-03-10T00:00:00+00:00 [running]> on host 2832635d2b45
[2024-05-29T17:03:02.536+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_1' AIRFLOW_CTX_TASK_ID='task_4' AIRFLOW_CTX_EXECUTION_DATE='2024-03-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-10T00:00:00+00:00'
[2024-05-29T17:03:02.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T17:03:02.603+0000] {logging_mixin.py:188} INFO - Run function_3!
[2024-05-29T17:03:02.617+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-29T17:03:02.633+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T17:03:02.686+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=test_1, task_id=task_4, run_id=scheduled__2024-03-10T00:00:00+00:00, execution_date=20240310T000000, start_date=20240529T170300, end_date=20240529T170302
[2024-05-29T17:03:02.839+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T17:03:03.177+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T17:03:03.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
